version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: trip_one_postgres
    environment:
      POSTGRES_DB: trip_one
      POSTGRES_USER: trip_one
      POSTGRES_PASSWORD: trip_one
    ports:
      - "5432:5432"
    volumes:
      - trip_one_data:/var/lib/postgresql/data

volumes:
  trip_one_data:
